### ISSUE TITLE
Error msg trying to run stock_extractor

### ISSUE THREAD

**Issue by ABQJuan** [ZachLiuGIS/stock_extractor#1]
Trying to run:
from stock_extractor import SP500Extractor

extractor = SP500Extractor()
sp500_symbols = extractor.get_sp500_symbol_list()

Receiving error msg:
Traceback (most recent call last):
  File "C:/Python27/Fundamentals/SP500Extractor.py", line 2, in <module>
    from stock_extractor import SP500Extractor
  File "C:\Users\johnf\Anaconda2\lib\site-packages\stock_extractor__init__.py", line 1, in <module>
    from stock_extractor.BarchartExtractor.sp_500_extract import SP500Extractor
ImportError: No module named BarchartExtractor.sp_500_extract

Please advise. Thanks!

**Comment by ghost** [comment]
Same thing for me. Also using the current git version
